
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Melbourne bom radar loop image
camera:
  - platform: bom
    location: Melbourne

  # Remote camera 0 - currentImage
  - platform: local_file
    name: remoteCam0_currentImage
    file_path: /config/www/remoteCam0_currentImage.jpg

  # Remote camera 0 - last motion
  - platform: local_file
    name: remoteCam0_lastMotion
    file_path: /config/www/remoteCam0_lastMotion.jpg

  # Remote camera 0 - timelapse
  - platform: local_file
    name: remoteCam0_timelapse
    file_path: /config/www/remoteCam0_timelapse.gif

weather:
  - platform: bom
    name: Viewbank
    station: IDV60901.95874

  - platform: bom
    name: Redesdale
    station: IDV60801.94859

mqtt:
    broker: 192.168.0.55

# Sensors
sensor:
  # Remote camera 0
  - platform: mqtt
    name: 'remoteCamera0/lastPing'
    state_topic: "remoteCamera0/lastPing"


  - platform: mqtt
    name: 'remoteCamera0/motionValue'
    state_topic: "remoteCamera0/motionValue"
    unit_of_measurement: "%"

  - platform: mqtt
    name: 'remoteCamera0/battVoltage'
    state_topic: "remoteCamera0/battVoltage"
    unit_of_measurement: "V"


  # Remote Camera 1


  # Remote sensor 0
  - platform: mqtt
    name: 'remoteSensor0/motionValue'
    state_topic: "remoteSensor0/motionValue"
    unit_of_measurement: "%"


  - platform: bom
    station: IDV60901.95874
    name: Viewbank
    monitored_conditions:
      - apparent_t # the feels like temperature
      - cloud # cloud cover
      - cloud_base_m
      - cloud_oktas # oktas of cloud cover
      - cloud_type # Types of clouds
      - gust_kmh
      - air_temp # Actual airtemp
      - dewpt # dew point
      - press # pressure in mbar
      - press_tend # pressure trend ??
      - rain_trace # amount of rain today in mm
      - rel_hum # relative humidity in %
      - weather # weather text summary
      - wind_dir # wind direction
      - wind_spd_kmh # wind speed in km/hr

  - platform: bom
    name: Redesdale
    station: IDV60801.94859
    monitored_conditions:
      - apparent_t # the feels like temperature
      - cloud # cloud cover
      - cloud_base_m
      - cloud_oktas # oktas of cloud cover
      - cloud_type # Types of clouds
      - gust_kmh
      - air_temp # Actual airtemp
      - dewpt # dew point
      - press # pressure in mbar
      - press_tend # pressure trend ??
      - rain_trace # amount of rain today in mm
      - rel_hum # relative humidity in %
      - weather # weather text summary
      - wind_dir # wind direction
      - wind_spd_kmh # wind speed in km/hr
