
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Melbourne bom radar loop image
camera:
  - platform: bom
    location: Melbourne

  ######### Remote Camera 0 ###########
  # Remote camera 0 - currentImage
  - platform: local_file
    name: remoteCam0_currentImage
    file_path: /config/www/remoteCam0_currentImage.jpg

  # Remote camera 0 - last motion
  - platform: local_file
    name: remoteCam0_lastMotion
    file_path: /config/www/remoteCam0_lastMotion.jpg

  # Remote camera 0 - timelapse
  - platform: local_file
    name: remoteCam0_timelapse
    file_path: /config/www/remoteCam0_timelapse.gif


  ######### Remote Camera 1 ###########
  # Remote camera 1 - currentImage
  - platform: local_file
    name: remoteCam1_currentImage
    file_path: /config/www/remoteCam1_currentImage.jpg

  # Remote camera 1 - last motion
  - platform: local_file
    name: remoteCam1_lastMotion
    file_path: /config/www/remoteCam1_lastMotion.jpg

  # Remote camera 1 - timelapse
  - platform: local_file
    name: remoteCam1_timelapse
    file_path: /config/www/remoteCam1_timelapse.gif

weather:
  - platform: bom
    name: Viewbank
    station: IDV60901.95874

  - platform: bom
    name: Redesdale
    station: IDV60801.94859

mqtt:
    broker: 192.168.0.55

# enable the recorder integration (optional)
recorder:
    purge_keep_days: 30
    purge_interval: 5

# Add the logbook card availability
logbook:

# Add an RSS feed reader
# Example configuration.yaml entry
feedreader:
  urls:
    - http://www.bom.gov.au/fwo/IDZ00059.warnings_vic.xml



# Sensors
sensor:

#  - platform: feedparser
#    name: Engineering Feed
#    feed_url: 'https://www.sciencedaily.com/rss/matter_energy/engineering.xml'
#    date_format: '%a, %b %d %I:%M %p'
#    inclusions:
#      - title
#      - link
#      - description
#      - image
#      - language
#      - pubDate
#    exclusions:
#      - language

  # Remote camera 0
  - platform: mqtt
    name: 'remoteCamera0/lastPing'
    state_topic: "remoteCamera0/lastPing"


  - platform: mqtt
    name: 'remoteCamera0/motionValue'
    state_topic: "remoteCamera0/motionValue"
    unit_of_measurement: "%"

  # Remote sensor 0
  - platform: mqtt
    name: 'remoteSensor0/motionValue'
    state_topic: "remoteSensor0/motionValue"
    unit_of_measurement: "%"

  - platform: mqtt
    name: 'remoteCamera0/battVoltage'
    state_topic: "remoteCamera0/battVoltage"
    unit_of_measurement: "V"


  # Remote Camera 1
  - platform: mqtt
    name: 'remoteCamera1/lastPing'
    state_topic: "remoteCamera1/lastPing"


  - platform: mqtt
    name: 'remoteCamera1/motionValue'
    state_topic: "remoteCamera1/motionValue"
    unit_of_measurement: "%"

  - platform: mqtt
    name: 'remoteCamera1/battVoltage'
    state_topic: "remoteCamera1/battVoltage"
    unit_of_measurement: "V"

    # Smooth battery voltage
  - platform: filter
    name: "remotecamera1_battvoltage_smooth"
    entity_id: sensor.remotecamera1_battvoltage
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 2

  - platform: filter
    name: "remotecamera0_battvoltage_smooth"
    entity_id: sensor.remotecamera0_battvoltage
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 2

  # Remote sensor 1
  - platform: mqtt
    name: 'remoteSensor1/motionValue'
    state_topic: "remoteSensor1/motionValue"
    unit_of_measurement: "%"

  - platform: bom
    station: IDV60901.95874
    name: Viewbank
    monitored_conditions:
      - apparent_t # the feels like temperature
      - cloud # cloud cover
      - cloud_base_m
      - cloud_oktas # oktas of cloud cover
      - cloud_type # Types of clouds
      - gust_kmh
      - air_temp # Actual airtemp
      - dewpt # dew point
      - press # pressure in mbar
      - press_tend # pressure trend ??
      - rain_trace # amount of rain today in mm
      - rel_hum # relative humidity in %
      - weather # weather text summary
      - wind_dir # wind direction
      - wind_spd_kmh # wind speed in km/hr

  - platform: bom
    name: Redesdale
    station: IDV60801.94859
    monitored_conditions:
      - apparent_t # the feels like temperature
      - cloud # cloud cover
      - cloud_base_m
      - cloud_oktas # oktas of cloud cover
      - cloud_type # Types of clouds
      - gust_kmh
      - air_temp # Actual airtemp
      - dewpt # dew point
      - press # pressure in mbar
      - press_tend # pressure trend ??
      - rain_trace # amount of rain today in mm
      - rel_hum # relative humidity in %
      - weather # weather text summary
      - wind_dir # wind direction
      - wind_spd_kmh # wind speed in km/hr


  # For calculating weather stats
  - platform: statistics
    entity_id: sensor.bom_viewbank_rain_today
    max_age:
      hours: 30
  - platform: statistics
    entity_id: sensor.bom_redesdale_rain_today
    max_age:
      hours: 30



# Automations
# Add buttons for the start and stop of these services
#type: button
#name: Shutdown basestation
#entity: script.shutdown_basestation
#tap_action:
#  action: call-service
#  service: shell_command.shutdown_basestation
#
#type: button
#name: Restart basestation
#entity: script.shutdown_basestation
#tap_action:
#  action: call-service
#  service: shell_command.shutdown_basestation




# Example configuration.yaml entry
# Exposes service shell_command.restart_pow
shell_command:
  # Adding shell commands for the basestation
  restart_basestation: sudo reboot
  shutdown_basestation: sudo shutdown now

  # Adding shell commands for the remoteCameras
  restart_remoteCamera0: ssh 192.168.0.56 'sudo reboot'
  restart_remoteCamera1: ssh 192.168.0.56 'sudo reboot'
  shutdown_remoteCamera0: ssh 192.168.0.56 'sudo shutdown now'
  shutdown_remoteCamera1: ssh 192.168.0.56 'sudo shutdown now'

