
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Melbourne bom radar loop image
camera:
  - platform: bom
    location: Melbourne

  # Remote camera 0 - currentImage
  - platform: local_file
    name: remoteCam0_currentImage
    file_path: /config/www/remoteCam0_currentImage.jpg

  # Remote camera 0 - last motion
  - platform: local_file
    name: remoteCam0_lastMotion
    file_path: /config/www/remoteCam0_lastMotion.jpg

  # Remote camera 0 - timelapse
  - platform: local_file
    name: remoteCam0_timelapse
    file_path: /config/www/remoteCam0_timelapse.gif

weather:
  - platform: bom
    name: Viewbank
    station: IDV60901.95874

  - platform: bom
    name: Reedsdale
    station: IDV60801.94859

mqtt:
    broker: 192.168.0.55

# Sensors
sensor:
  # Remote camera 0
  - platform: mqtt
    name: 'Last Ping'
    state_topic: "remoteCamera0/lastPing"
    unit_of_measurement: "%"


  - platform: mqtt
    name: 'Motion'
    state_topic: "remoteCamera0/motionValue"
    unit_of_measurement: "%"

  - platform: mqtt
    name: 'Voltage'
    state_topic: "remoteCamera0/battVoltage"
    unit_of_measurement: "V"


  # Remote Camera 1


  # Remote sensor 0
  - platform: mqtt
    name: 'Remote Sensor 0 Value'
    state_topic: "remoteSensor0/motionValue"
    unit_of_measurement: "%"
