name: sensor.feedparser
description: 📰 RSS feed custom component for Home Assistant
type: component
keywords:
  - sensor
  - feedparser
  - rss
  - feed
  - list
author:
  name: Ian Richardson
  email: iantrich@gmail.com
  homepage: https://iantrich.github.io
license: MIT
files:
  - custom_components/feedparser/sensor.py
  - custom_components/feedparser/manifest.json
